### PR TITLE
ENH: various enhancements with the goal of making the tool work

### PR DESCRIPTION
**Pull request by klauer**
## Description
* Add 'groupinstall' support for system packages with yum
* Fix up command-line processing of spec file / environment file listing (again)
* Create a directory for `RELEASE_SITE` if missing
* Add preliminary system package introspection, built on and enhancing whatrecord's Makefile introspection tool
   * Also provides details for the names of libraries that get linked for an application binary. How useful that is remains to be seen...

## Motivation and Context
Goal: make it work

### CODE REVIEW

**Comment by klauer** [comment]
whatrecord is now on conda-forge; cycling this PR for CI

**Comment by klauer** [comment]
This is a checkpoint PR; since I dropped it a few months ago we should merge and I'll move forward with another PR

**Review by tangkong — APPROVED** [review]
yeah ok

**Review by ZLLentz — APPROVED** [review]

**Comment by tangkong** [comment]
oh this could use the addition of a "doc" section in pyproject.toml.  If you don't want to add that in this PR I can add an issue

**Comment by klauer** [comment]
> oh this could use the addition of a "doc" section in pyproject.toml. If you don't want to add that in this PR I can add an issue

Done in [3303bd3](https://github.com/pcdshub/pib/pull/2/commits/3303bd308d84b53bb7d54be8a72ab340ddfdc4d2)

**Pull request merged**
